command = ["nix-shell", "test/remote-behavior/env.nix", "--run", "bash test/remote-behavior/run.sh"]
junit = ["test/remote-behavior/results/junit.xml", "test/remote-behavior/results/projection-junit.xml"]
